# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f4bbd7b1e97add3df337b2ed4af91ca"
name = "prisjakt-produktfeed"
application_url = "https://drug-guy-mechanics-surely.trycloudflare.com"
embedded = true
handle = "prisjakt-produktfeed"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products"

[auth]
redirect_urls = ["https://drug-guy-mechanics-surely.trycloudflare.com/auth/callback", "https://drug-guy-mechanics-surely.trycloudflare.com/auth/shopify/callback", "https://drug-guy-mechanics-surely.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
